// 13. OCCUPATIONS
export const OCCUPATIONS = {
  SOFTWARE_ENGINEER: 'Software Engineer',
  ACTOR: 'ACTOR',
  ACTRESS: 'ACTRESS',
  ARTIST: 'Artist',
  MUSICIAN: 'Musician',
  DOCTOR: 'Doctor',
  NURSE: 'Nurse',
  PHARMACIST: 'Pharmacist',
  DENTIST: 'Dentist',
  SURGEON: 'Surgeon',
  TEACHER: 'Teacher',
  PROFESSOR: 'Professor',
  LECTURER: 'Lecturer',
  LAWYER: 'Lawyer',
  JUDGE: 'Judge',
  ACCOUNTANT: 'Accountant',
  CHARTERED_ACCOUNTANT: 'Chartered Accountant',
  BANKER: 'Banker',
  FINANCIAL_ANALYST: 'Financial Analyst',
  BUSINESS_OWNER: 'Business Owner',
  ENTREPRENEUR: 'Entrepreneur',
  SALES_MANAGER: 'Sales Manager',
  MARKETING_MANAGER: 'Marketing Manager',
  HR_MANAGER: 'HR Manager',
  PROJECT_MANAGER: 'Project Manager',
  PRODUCT_MANAGER: 'Product Manager',
  DATA_ANALYST: 'Data Analyst',
  DATA_SCIENTIST: 'Data Scientist',
  UI_UX_DESIGNER: 'UI/UX Designer',
  GRAPHIC_DESIGNER: 'Graphic Designer',
  ARCHITECT: 'Architect',
  CIVIL_ENGINEER: 'Civil Engineer',
  MECHANICAL_ENGINEER: 'Mechanical Engineer',
  ELECTRICAL_ENGINEER: 'Electrical Engineer',
  GOVERNMENT_OFFICER: 'Government Officer',
  ADMIN_OFFICER: 'Administrative Officer',
  POLICE_OFFICER: 'Police Officer',
  MILITARY_OFFICER: 'Military Officer',
  PILOT: 'Pilot',
  CABIN_CREW: 'Cabin Crew',
  CHEF: 'Chef',
  HOMEMAKER: 'Homemaker',
  HOSPITALITY_MANAGER: 'Hospitality Manager',
  HOTEL_MANAGER: 'Hotel Manager',
  FASHION_DESIGNER: 'Fashion Designer',
  JOURNALIST: 'Journalist',
  CONTENT_CREATOR: 'Content Creator',
  SOCIAL_WORKER: 'Social Worker',
  PSYCHOLOGIST: 'Psychologist',
  RESEARCHER: 'Researcher',
  SCIENTIST: 'Scientist',
  CONSULTANT: 'Consultant',
  REAL_ESTATE_AGENT: 'Real Estate Agent',
  AGRICULTURIST: 'Agriculturist',
  STUDENT: 'Student',
  OTHER: 'Other',
} as const;
export type OccupationKey = keyof typeof OCCUPATIONS;

// 14. HIGHEST EDUCATION
export const HIGHEST_EDUCATION = {
  HIGH_SCHOOL: 'High School Graduate',
  ASSOCIATES: "Associate's Degree",
  BACHELORS: "Bachelor's Degree",
  MASTERS: "Master's Degree",
  DOCTORATE: 'Doctorate',
  DIPLOMA: 'Diploma/Trade School',
  OTHER: 'Other',
} as const;
export type HighestEducationKey = keyof typeof HIGHEST_EDUCATION;
